apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-notes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-notes
  template:
    metadata:
      labels:
        app: django-notes
    spec:
      containers:
        - name: django-notes
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000

