apiVersion: v1
kind: Service
metadata:
  name: django-notes
  namespace: notes-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: django-notes
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}

